Remove cantera from setup.py
ecisneros8/pyrometheus pull request #26
Opened 2021-05-24 18:36 UTC by matthiasdiener

`pip install cantera` does not work.

CC: @MTCam

2021-05-24 19:02 UTC, inducer requested changes
> `pip install cantera` does not work.

IMO: `setup.py` declares dependencies that need to be installed. Its job is not to provide installation instructions. Of course it's nice if `pip install` just works, but that's not entirely realistic for cantera.

2021-05-24 19:36 UTC, matthiasdiener commented
> > `pip install cantera` does not work.
> 
> IMO: `setup.py` declares dependencies that need to be installed. Its job is not to provide installation instructions. Of course it's nice if `pip install` just works, but that's not entirely realistic for cantera.

Right, but doesn't this break pyrometheus installation?

```
~/Work/pyrometheus (main =) $ python setup.py install
running install
running bdist_egg
running egg_info
creating pyrometheus.egg-info
writing pyrometheus.egg-info/PKG-INFO
writing dependency_links to pyrometheus.egg-info/dependency_links.txt
writing requirements to pyrometheus.egg-info/requires.txt
writing top-level names to pyrometheus.egg-info/top_level.txt
writing manifest file 'pyrometheus.egg-info/SOURCES.txt'
reading manifest file 'pyrometheus.egg-info/SOURCES.txt'
writing manifest file 'pyrometheus.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-11.0-arm64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pyrometheus
copying pyrometheus/version.py -> build/lib/pyrometheus
copying pyrometheus/__init__.py -> build/lib/pyrometheus
creating build/bdist.macosx-11.0-arm64
creating build/bdist.macosx-11.0-arm64/egg
creating build/bdist.macosx-11.0-arm64/egg/pyrometheus
copying build/lib/pyrometheus/version.py -> build/bdist.macosx-11.0-arm64/egg/pyrometheus
copying build/lib/pyrometheus/__init__.py -> build/bdist.macosx-11.0-arm64/egg/pyrometheus
byte-compiling build/bdist.macosx-11.0-arm64/egg/pyrometheus/version.py to version.cpython-38.pyc
byte-compiling build/bdist.macosx-11.0-arm64/egg/pyrometheus/__init__.py to __init__.cpython-38.pyc
creating build/bdist.macosx-11.0-arm64/egg/EGG-INFO
copying pyrometheus.egg-info/PKG-INFO -> build/bdist.macosx-11.0-arm64/egg/EGG-INFO
copying pyrometheus.egg-info/SOURCES.txt -> build/bdist.macosx-11.0-arm64/egg/EGG-INFO
copying pyrometheus.egg-info/dependency_links.txt -> build/bdist.macosx-11.0-arm64/egg/EGG-INFO
copying pyrometheus.egg-info/requires.txt -> build/bdist.macosx-11.0-arm64/egg/EGG-INFO
copying pyrometheus.egg-info/top_level.txt -> build/bdist.macosx-11.0-arm64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pyrometheus-2020.1-py3.8.egg' and adding 'build/bdist.macosx-11.0-arm64/egg' to it
removing 'build/bdist.macosx-11.0-arm64/egg' (and everything under it)
Processing pyrometheus-2020.1-py3.8.egg
Copying pyrometheus-2020.1-py3.8.egg to /Users/mdiener/Work/emirge_lazy/miniforge3/envs/ceesd_lazy/lib/python3.8/site-packages
Removing pyrometheus 2020.1 from easy-install.pth file
Adding pyrometheus 2020.1 to easy-install.pth file

Installed /Users/mdiener/Work/emirge_lazy/miniforge3/envs/ceesd_lazy/lib/python3.8/site-packages/pyrometheus-2020.1-py3.8.egg
Processing dependencies for pyrometheus==2020.1
Searching for cantera
Reading https://pypi.org/simple/cantera/
Couldn't find index page for 'cantera' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for cantera
error: Could not find suitable distribution for Requirement.parse('cantera')
```

2021-05-24 19:42 UTC, inducer commented
To me, what you show is exactly the correct behavior. It's not possible (and *shouldn't be possible*) to install pyrometheus without installing cantera beforehand.

2021-05-25 14:25 UTC, MTCam commented
> To me, what you show is exactly the correct behavior. It's not possible (and _shouldn't be possible_) to install pyrometheus without installing cantera beforehand.

One problem we are having is that this breaks `emirge` and therefore `mirgecom` installs at least on Lassen. @matthiasdiener, is this the culprit? I desperately would like to get the timing runs going again, and this seems like the last (at least the current) hurdle.

2021-05-25 14:33 UTC, matthiasdiener commented
> > To me, what you show is exactly the correct behavior. It's not possible (and _shouldn't be possible_) to install pyrometheus without installing cantera beforehand.
> 
> One problem we are having is that this breaks `emirge` and therefore `mirgecom` installs at least on Lassen. @matthiasdiener, is this the culprit? I desperately would like to get the timing runs going again, and this seems like the last (at least the current) hurdle.

I believe the root of the issue is this: https://github.com/conda/conda/issues/10133 . This PR just works around it.

2021-05-25 14:51 UTC, MTCam commented
> > > To me, what you show is exactly the correct behavior. It's not possible (and _shouldn't be possible_) to install pyrometheus without installing cantera beforehand.
> > 
> > 
> > One problem we are having is that this breaks `emirge` and therefore `mirgecom` installs at least on Lassen. @matthiasdiener, is this the culprit? I desperately would like to get the timing runs going again, and this seems like the last (at least the current) hurdle.
> 
> I believe the root of the issue is this: [conda/conda#10133](https://github.com/conda/conda/issues/10133) . This PR just works around it.

Awesome, thanks!  If it does no harm here to Pyrometheus, then is there any chance we could get it applied, at least temporarily, so that we can use emirge?  Either that, or should we point mirgecom@main to this branch?

2021-05-25 14:52 UTC, matthiasdiener commented
> > > > To me, what you show is exactly the correct behavior. It's not possible (and _shouldn't be possible_) to install pyrometheus without installing cantera beforehand.
> > > 
> > > 
> > > One problem we are having is that this breaks `emirge` and therefore `mirgecom` installs at least on Lassen. @matthiasdiener, is this the culprit? I desperately would like to get the timing runs going again, and this seems like the last (at least the current) hurdle.
> > 
> > 
> > I believe the root of the issue is this: [conda/conda#10133](https://github.com/conda/conda/issues/10133) . This PR just works around it.
> 
> Awesome, thanks! If it does no harm here to Pyrometheus, then is there any chance we could get it applied, at least temporarily, so that we can use emirge? Either that, or should we point mirgecom@main to this branch?

I'll try to find another workaround, maybe there is a better way.

2021-05-26 21:27 UTC, matthiasdiener commented
Closing in favor of https://github.com/illinois-ceesd/emirge/pull/132

2021-05-26 21:27 UTC, closed without merging